import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";
import type { ColorPalette, TypographySuggestion } from "@/types";

export async function POST(request: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { brandName, industry, style, result } = await request.json();

  const palettes = (result.color_palettes || []) as ColorPalette[];
  const typography = (result.typography || []) as TypographySuggestion[];
  const slogans = (result.slogans || []) as string[];
  const p = palettes[0] || { primary: "#7C3AED", secondary: "#2563EB", accent: "#EC4899", background: "#030303", text: "#ffffff" };

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${brandName} — Brand Kit</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=Inter:wght@300;400;500;600&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', sans-serif; background: #030303; color: #ffffff; min-height: 100vh; }
  .page { max-width: 860px; margin: 0 auto; padding: 48px 24px; }
  .header { text-align: center; padding: 60px 0 48px; border-bottom: 1px solid rgba(255,255,255,0.06); margin-bottom: 48px; }
  .badge { display: inline-flex; align-items: center; gap: 8px; padding: 6px 16px; border-radius: 999px; background: rgba(124,58,237,0.15); border: 1px solid rgba(124,58,237,0.3); color: #a78bfa; font-size: 12px; font-weight: 500; margin-bottom: 20px; }
  h1 { font-family: 'Syne', sans-serif; font-size: clamp(40px, 6vw, 72px); font-weight: 800; background: linear-gradient(135deg, #a78bfa, #60a5fa, #f472b6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; margin-bottom: 12px; }
  .sub { font-size: 16px; color: rgba(255,255,255,0.4); text-transform: capitalize; }
  .section { margin-bottom: 48px; }
  .section-title { font-family: 'Syne', sans-serif; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 3px; color: rgba(255,255,255,0.3); margin-bottom: 20px; display: flex; align-items: center; gap: 8px; }
  .section-title::after { content: ''; flex: 1; height: 1px; background: rgba(255,255,255,0.06); }
  .card { background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.06); border-radius: 16px; padding: 20px; margin-bottom: 12px; }
  .prompt-box { font-family: monospace; font-size: 13px; line-height: 1.8; color: rgba(255,255,255,0.7); background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.06); border-radius: 12px; padding: 20px; white-space: pre-wrap; }
  .color-strip { display: flex; height: 64px; border-radius: 12px; overflow: hidden; margin-bottom: 16px; }
  .color-seg { flex: 1; }
  .color-swatches { display: flex; gap: 12px; flex-wrap: wrap; }
  .swatch { display: flex; align-items: center; gap: 8px; }
  .swatch-dot { width: 20px; height: 20px; border-radius: 6px; }
  .swatch-label { font-size: 12px; color: rgba(255,255,255,0.5); }
  .swatch-hex { font-family: monospace; font-size: 12px; color: rgba(255,255,255,0.7); }
  .palette-name { font-family: 'Syne', sans-serif; font-size: 14px; font-weight: 600; color: rgba(255,255,255,0.8); margin-bottom: 12px; }
  .slogan-item { padding: 14px 18px; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.06); border-radius: 12px; margin-bottom: 8px; font-size: 15px; color: rgba(255,255,255,0.8); font-style: italic; }
  .font-row { display: flex; align-items: baseline; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid rgba(255,255,255,0.04); }
  .font-role { font-size: 11px; text-transform: uppercase; letter-spacing: 2px; color: rgba(255,255,255,0.3); width: 80px; shrink: 0; }
  .font-name { font-size: 15px; font-weight: 600; color: rgba(255,255,255,0.8); }
  .footer { text-align: center; padding: 40px 0 20px; border-top: 1px solid rgba(255,255,255,0.06); margin-top: 60px; }
  .footer p { font-size: 12px; color: rgba(255,255,255,0.2); }
  .footer a { color: #a78bfa; text-decoration: none; }
  @media print {
    body { background: white; color: black; }
    .header, .section, .footer { page-break-inside: avoid; }
  }
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <div class="badge">✦ Generated by BrandForge AI</div>
    <h1>${brandName}</h1>
    <div class="sub">${industry} &middot; ${style} design</div>
  </div>

  ${result.logo_prompt ? `
  <div class="section">
    <div class="section-title">🎨 Logo Prompt</div>
    <div class="prompt-box">${result.logo_prompt}</div>
    <p style="margin-top:10px; font-size:12px; color:rgba(255,255,255,0.3)">
      Copy this prompt into Midjourney, DALL-E 3, or Stable Diffusion to generate your logo
    </p>
  </div>` : ""}

  ${slogans.length > 0 ? `
  <div class="section">
    <div class="section-title">💬 Brand Slogans</div>
    ${slogans.map(s => `<div class="slogan-item">"${s}"</div>`).join("")}
  </div>` : ""}

  ${palettes.length > 0 ? `
  <div class="section">
    <div class="section-title">🎨 Color Palettes</div>
    ${palettes.map(pal => `
    <div class="card">
      <div class="palette-name">${pal.name}</div>
      <div class="color-strip">
        <div class="color-seg" style="background:${pal.primary}"></div>
        <div class="color-seg" style="background:${pal.secondary}"></div>
        <div class="color-seg" style="background:${pal.accent}"></div>
        <div class="color-seg" style="background:${pal.background}"></div>
        <div class="color-seg" style="background:${pal.text}"></div>
      </div>
      <div class="color-swatches">
        ${[{l:"Primary",v:pal.primary},{l:"Secondary",v:pal.secondary},{l:"Accent",v:pal.accent},{l:"Background",v:pal.background},{l:"Text",v:pal.text}]
          .map(c=>`<div class="swatch"><div class="swatch-dot" style="background:${c.v}"></div><span class="swatch-label">${c.l}</span><span class="swatch-hex">${c.v}</span></div>`).join("")}
      </div>
      ${pal.description ? `<p style="margin-top:12px;font-size:12px;color:rgba(255,255,255,0.3)">${pal.description}</p>` : ""}
    </div>`).join("")}
  </div>` : ""}

  ${typography.length > 0 ? `
  <div class="section">
    <div class="section-title">✍️ Typography</div>
    ${typography.map((t, i) => `
    <div class="card">
      <div class="palette-name">Pairing ${i+1} &mdash; ${t.mood}</div>
      <div class="font-row"><span class="font-role">Heading</span><span class="font-name">${t.heading}</span></div>
      <div class="font-row"><span class="font-role">Body</span><span class="font-name">${t.body}</span></div>
      <div class="font-row" style="border:0"><span class="font-role">Accent</span><span class="font-name">${t.accent}</span></div>
      ${t.pairing_reason ? `<p style="margin-top:12px;font-size:12px;color:rgba(255,255,255,0.3)">${t.pairing_reason}</p>` : ""}
    </div>`).join("")}
  </div>` : ""}

  ${result.brand_names && result.brand_names.length > 0 ? `
  <div class="section">
    <div class="section-title">💡 Alternative Brand Names</div>
    <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:10px">
      ${(result.brand_names as string[]).map(n=>`<div class="card" style="text-align:center;font-family:Syne,sans-serif;font-weight:700;font-size:15px;padding:14px">${n}</div>`).join("")}
    </div>
  </div>` : ""}

  <div class="footer">
    <p>Generated by <a href="https://logo-ai-generator-two.vercel.app">BrandForge AI</a> &middot; ${new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}</p>
  </div>
</div>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${brandName.replace(/\s+/g, "-").toLowerCase()}-brand-kit.html"`,
    },
  });
}
